-- Seed Data: Cases 11-20

INSERT INTO cases (id, title, description, difficulty, category, starting_code, expected_output, suspects_json, evidence_json, xp_reward) VALUES 
(11, 'The Scope Spectre', 
 'A detective tried to identify the killer using a global variable, but a local variable shadowed it. The output keeps saying "Unknown". Fix the scope issue to reveal the global killer name.', 
 'Medium', 'Scope', 
 'killer = "Mr. Global"\ndef identify_killer():\n    killer = "Unknown"\n    return killer\nprint(identify_killer())', 
 'Mr. Global', 
 '[{"name": "Glo Bal", "bio": "Visible everywhere."}, {"name": "Lo Cal", "bio": "Keeps to himself."}]',
 '["A confusing police report."]',
 300),

(12, 'The Modulo Motive', 
 'The security code cycles every 7 days. The crime happened on day 50. Use the modulo operator to find the equivalent day in the 7-day cycle (0-6).', 
 'Medium', 'Math', 
 'cycle = 7\nday = 50\n# Find the remainder\nsecurity_day = 0 # Fix this\nprint(security_day)', 
 '1', 
 '[{"name": "Rem Ainder", "bio": "Always left over."}, {"name": "Div Ider", "bio": "Splits things up."}]',
 '["A cyclic calendar."]',
 300),

(13, 'The Import Imposter', 
 'To solve the tox screen, you need to calculate the square root of the toxicity level. However, the math module is missing. Import the math module and use sqrt.', 
 'Medium', 'Modules', 
 '# import the module here\ntoxicity = 16\nlevel = math.sqrt(toxicity)\nprint(int(level))', 
 '4', 
 '[{"name": "Im Port", "bio": "Brings things in."}, {"name": "Ex Port", "bio": "Sends things out."}]',
 '["A chemistry set missing instructions."]',
 350),

(14, 'The Exception Execution', 
 'A corrupted file causes the evidence processor to crash with a ZeroDivisionError. Wrap the risky code in a try-except block to handle the error and print "Error Detected" instead of crashing.', 
 'Medium', 'Exceptions', 
 'evidence_count = 0\ntotal_weight = 100\n# This crashes if count is 0\nratio = total_weight / evidence_count\nprint(ratio)', 
 'Error Detected', 
 '[{"name": "Try Catch", "bio": "Always prepared for the worst."}, {"name": "Crash Override", "bio": "Breaks everything."}]',
 '["A blue screen of death."]',
 350),

(15, 'The File Forensics', 
 'We have intercepted a data stream as a multi-line string. We need to count how many times the word "KILL" appears in the log. Use string methods to count.', 
 'Medium', 'String Methods', 
 'log = "INFO: LOGIN\\nWARN: KILL PROCESS\\nINFO: LOGOUT\\nWARN: KILL THREAD"\n# Count "KILL"\ncount = 0\nprint(count)', 
 '2', 
 '[{"name": "Count Von Count", "bio": "Loves numbers."}, {"name": "Find Lay", "bio": "Good at searching."}]',
 '["A server log printout."]',
 400),

(16, 'The List Comp Conspiracy', 
 'We represent interrogation room numbers as a list of integers [1, 2, 3, 4, 5]. We need a new list of only the even numbered rooms where the suspects are held. Use a list comprehension.', 
 'Medium', 'List Comprehensions', 
 'rooms = [1, 2, 3, 4, 5]\n# Create a list of even rooms only\nsuspect_rooms = []\nprint(suspect_rooms)', 
 '[2, 4]', 
 '[{"name": "Comp Rehension", "bio": "Short and concise."}, {"name": "For Looper", "bio": "Long winded."}]',
 '["A map of the station."]',
 400),

(17, 'The Set Setup', 
 'Suspects gave conflicting alibis locations. We need a list of UNIQUE locations mentioned. Converting the list to a Set is the fastest way. Output the number of unique locations.', 
 'Medium', 'Sets', 
 'locations = ["Park", "Bar", "Park", "Cinema", "Bar"]\nlimit = 0\n# Find unique count\nprint(limit)', 
 '3', 
 '[{"name": "Uni Que", "bio": "One of a kind."}, {"name": "Dup Licate", "bio": "Copycat."}]',
 '["A scribbled list of alibis."]',
 450),

(18, 'The Arg Assassin', 
 'The assassin used a function that takes a variable number of weapons using *args. The current call only passes one. Update the function call (NOT the definition) to pass "Dagger", "Gun", "Poison" and print the total count.', 
 'Medium', 'Arguments', 
 'def count_weapons(*args):\n    return len(args)\n\n# Pass "Dagger", "Gun", "Poison"\ncount = count_weapons("Dagger")\nprint(count)', 
 '3', 
 '[{"name": "Star Args", "bio": "Can handle any number of things."}, {"name": "Fix Ed", "bio": "Rigid and inflexible."}]',
 '["An arsenal inventory."]',
 450),

(19, 'The Reference Ruse', 
 'A suspect list was copied, but modify the copy also modified the original because of a shallow copy reference. Use `.copy()` or slicing to make a true independent copy before modifying.', 
 'Medium', 'References', 
 'original_list = ["A", "B"]\n# Make a real copy here\nnew_list = original_list\nnew_list.append("C")\n# Original should still be ["A", "B"]\nprint(original_list)', 
 '[\'A\', \'B\']', 
 '[{"name": "Ref Erence", "bio": "Attached at the hip."}, {"name": "Clo Ne", "bio": "An exact independent replica."}]',
 '["Two identical dossiers."]',
 500),

(20, 'The Recursion Riddler', 
 'The encryption key is the 6th Fibonacci number. Implement a recursive function to calculate fib(6). Sequence: 0, 1, 1, 2, 3, 5, 8...', 
 'Hard', 'Recursion', 
 'def fib(n):\n    if n <= 1: return n\n    return 0 # Fix logic\nprint(fib(6))', 
 '8', 
 '[{"name": "Re Cursion", "bio": "Repeats himself."}, {"name": "Base Case", "bio": "Stops the madness."}]',
 '["A spiral sequence drawn on the wall."]',
 500);
