-- Seed Data: Cases 1-5

INSERT INTO cases (id, title, description, difficulty, category, starting_code, expected_output, suspects_json, evidence_json, xp_reward) VALUES 
(1, 'The Variable Victim', 
 'In the dim light of a server room, a junior dev was found "terminated". The only clue is a script on his terminal that calculates the time of death, but the variables are all mixed up. Fix the variable assignment to reveal the true time of death.', 
 'Easy', 'Variables', 
 'death_hour = "11"\ndeath_minute = 30\n# The killer struck when the minute hand was at 0.\nprint("Time of Death: " + death_hour + ":" + death_minute)', 
 'Time of Death: 11:00', 
 '[{"name": "Victor Var", "bio": "A chaotic programmer who never names variables correctly."}, {"name": "Sid Syntax", "bio": "Obsessed with clean code, hated the victim."}, {"name": "Lara Logic", "bio": "The team lead."}]',
 '["A broken python script running on the victims screen.", "A watch stopped at 11:00."]',
 100),

(2, 'The Typo Tycoon', 
 'Billionaire Data Mogul, Mr. Float, was poisoned. His smart-lock ledger has a bug preventing the investigative team from accessing his last meal logs. The system is failing because of a type mismatch. Cast the types correctly to unlock the log.', 
 'Easy', 'Data Types', 
 'price = "500"\nquantity = 2\ntotal = price * quantity\nprint(total)', 
 '1000', 
 '[{"name": "Penny String", "bio": "Claims she has no value."}, {"name": "Inty Integer", "bio": "A rigid accountant."}]',
 '["A receipt showing a total of 1000.", "A python error log on the smart lock."]',
 100),

(3, 'The Sliced Silhouette', 
 'A ransom note was found, but it is gibberish. Use string slicing to decode the hidden location of the suspect. The note says "XLOCATION:DOCKS_WAREHOUSE_9Z". extract only the location name.', 
 'Easy', 'Strings', 
 'note = "XLOCATION:DOCKS_WAREHOUSE_9Z"\n# Extract "DOCKS_WAREHOUSE_9"\nlocation = note[0:5]\nprint(location)', 
 'DOCKS_WAREHOUSE_9', 
 '[{"name": "Sam Slicer", "bio": "Known for cutting corners."}, {"name": "Madam Index", "bio": "Always knows where things are."}]',
 '["An encrypted note.", "A pair of scissors."]',
 150),

(4, 'The Listless Body', 
 'A list of attendees at the charity gala was tampered with. The killers name was removed, but a ghost entry remains. The police need you to access the last known element of the list, which contains the killers signature.', 
 'Easy', 'Lists', 
 'guests = ["Mayor", "Doctor", "Killer", "Chef"]\n# The killer deleted the last element, but the memory remains.\n# Print the last element of the list dynamically.\nprint(guests[4])', 
 'Chef', 
 '[{"name": "Larry List", "bio": "Organizer of the list."}, {"name": "Ina Index", "bio": "Always out of bounds."}]',
 '["A guest list with a torn bottom edge."]',
 150),

(5, 'The Tuple Twist', 
 'The vault combination is stored in a tuple. Someone tried to change it to cover their tracks, but tuples are immutable, causing a system crash. Retrieve the original third number from the tuple to open the vault.', 
 'Easy', 'Tuples', 
 'combo = (12, 45, 99, 23)\n# The thief tried: combo[2] = 0\n# Just print the 3rd number (99) from the tuple.\nprint(combo[0])', 
 '99', 
 '[{"name": "Timmy Tuple", "bio": "Stubborn and unchanging."}, {"name": "Molly Mutable", "bio": "Loves to change things around."}]',
 '["A crashed security terminal."]',
 200);
