-- Seed Data: Cases 1-10

INSERT INTO cases (id, title, description, difficulty, category, starting_code, expected_output, suspects_json, evidence_json, xp_reward) VALUES 
(1, 'The Variable Victim', 
 'In the dim light of a server room, a junior dev was found "terminated". The only clue is a script on his terminal that calculates the time of death, but the variables are all mixed up. Fix the variable assignment to reveal the true time of death.', 
 'Easy', 'Variables', 
 'death_hour = "11"\ndeath_minute = 30\n# The killer struck when the minute hand was at 0.\nprint("Time of Death: " + death_hour + ":" + death_minute)', 
 'Time of Death: 11:00', 
 '[{"name": "Victor Var", "bio": "A chaotic programmer who never names variables correctly."}, {"name": "Sid Syntax", "bio": "Obsessed with clean code, hated the victim."}, {"name": "Lara Logic", "bio": "The team lead."}]',
 '["A broken python script running on the victims screen.", "A watch stopped at 11:00."]',
 100),

(2, 'The Typo Tycoon', 
 'Billionaire Data Mogul, Mr. Float, was poisoned. His smart-lock ledger has a bug preventing the investigative team from accessing his last meal logs. The system is failing because of a type mismatch. Cast the types correctly to unlock the log.', 
 'Easy', 'Data Types', 
 'price = "500"\nquantity = 2\ntotal = price * quantity\nprint(total)', 
 '1000', 
 '[{"name": "Penny String", "bio": "Claims she has no value."}, {"name": "Inty Integer", "bio": "A rigid accountant."}]',
 '["A receipt showing a total of 1000.", "A python error log on the smart lock."]',
 100),

(3, 'The Sliced Silhouette', 
 'A ransom note was found, but it is gibberish. Use string slicing to decode the hidden location of the suspect. The note says "XLOCATION:DOCKS_WAREHOUSE_9Z". Extract only the location name.', 
 'Easy', 'Strings', 
 'note = "XLOCATION:DOCKS_WAREHOUSE_9Z"\n# Extract "DOCKS_WAREHOUSE_9"\nlocation = note[0:5]\nprint(location)', 
 'DOCKS_WAREHOUSE_9', 
 '[{"name": "Sam Slicer", "bio": "Known for cutting corners."}, {"name": "Madam Index", "bio": "Always knows where things are."}]',
 '["An encrypted note.", "A pair of scissors."]',
 150),

(4, 'The Listless Body', 
 'A list of attendees at the charity gala was tampered with. The killers name was removed, but a ghost entry remains. The police need you to access the last known element of the list, which contains the killers signature.', 
 'Easy', 'Lists', 
 'guests = ["Mayor", "Doctor", "Killer", "Chef"]\n# The killer deleted the last element, but the memory remains.\n# Print the last element of the list dynamically.\nprint(guests[4])', 
 'Chef', 
 '[{"name": "Larry List", "bio": "Organizer of the list."}, {"name": "Ina Index", "bio": "Always out of bounds."}]',
 '["A guest list with a torn bottom edge."]',
 150),

(5, 'The Tuple Twist', 
 'The vault combination is stored in a tuple. Someone tried to change it to cover their tracks, but tuples are immutable, causing a system crash. Retrieve the original third number from the tuple to open the vault.', 
 'Easy', 'Tuples', 
 'combo = (12, 45, 99, 23)\n# The thief tried: combo[2] = 0\n# Just print the 3rd number (99) from the tuple.\nprint(combo[0])', 
 '99', 
 '[{"name": "Timmy Tuple", "bio": "Stubborn and unchanging."}, {"name": "Molly Mutable", "bio": "Loves to change things around."}]',
 '["A crashed security terminal."]',
 200),

(6, 'The Dictionary Deceit', 
 'A safe deposit box is locked with a key-value pair mechanism. The killer changed the key "Code" to "Cipher", but the system is still looking for "Code". Access the value associated with the new key "Cipher" to find the murder weapon.', 
 'Easy', 'Dictionaries', 
 'evidence_locker = {"Cipher": "Poison_Vial", "Money": "Missing"}\n# The system tries to access "Code", fix it to access "Cipher"\nweapon = evidence_locker["Code"]\nprint(weapon)', 
 'Poison_Vial', 
 '[{"name": "Kelly Key", "bio": "Always looking for the right fit."}, {"name": "Val Value", "bio": "Holds the secrets."}]',
 '["A safe deposit box log."]',
 200),

(7, 'The Conditional Killer', 
 'The security camera logs show a gap. The logic to save the footage has a flaw. It only saves if motion is greater than 10, but the killer moved slowly (motion = 5). Adjust the condition so it captures the footage even for slow movement.', 
 'Easy', 'Logic', 
 'motion_level = 5\nstatus = "Not Recording"\nif motion_level > 10:\n    status = "Recording"\nprint(status)', 
 'Recording', 
 '[{"name": "Ian If", "bio": "Only acts if conditions are met."}, {"name": "Elsa Else", "bio": "Always has a backup plan."}]',
 '["Security camera specs."]',
 200),

(8, 'The Loophole Logic', 
 'A for-loop was supposed to print the names of all 5 suspects, but it stops early. The killer is the last person on the list. Fix range() to include the last suspect.', 
 'Medium', 'Loops', 
 'suspects = ["Alice", "Bob", "Charlie", "Dave", "Eve"]\n# The loop misses Eve. Fix the range.\nfor i in range(0, 4):\n    print(suspects[i])', 
 'Alice\nBob\nCharlie\nDave\nEve', 
 '[{"name": "Ran Ge", "bio": "Known for his limits."}, {"name": "Ita Rator", "bio": "Repeats herself constantly."}]',
 '["A printed list with the bottom torn off."]',
 250),

(9, 'The While Witness', 
 'A witness interrogation bot is stuck in an infinite loop asking "Who did it?". It needs a break condition when the answer is "Red". Add the break logic.', 
 'Medium', 'Loops', 
 'answers = ["Blue", "Green", "Red", "Yellow"]\ni = 0\nwhile i < len(answers):\n    ans = answers[i]\n    print("Suspect says: " + ans)\n    # Stop if ans is "Red"\n    i += 1', 
 'Suspect says: Blue\nSuspect says: Green\nSuspect says: Red', 
 '[{"name": "Bre Aker", "bio": "Stops things abruptly."}, {"name": "Con Tinue", "bio": "Keeps going no matter what."}]',
 '["A frozen robot."] ',
 250),

(10, 'The Function Fatal', 
 'The toxicology report uses a function that returns nothing (None), but the detective expects a string. The `return` statement is missing. Fix the function to return the toxin name.', 
 'Medium', 'Functions', 
 'def analyze_blood():\n    toxin = "Arsenic"\n    # Something is missing here\n\nresult = analyze_blood()\nprint("Found: " + str(result))', 
 'Found: Arsenic', 
 '[{"name": "Ret Urn", "bio": "Always gives back what is owed."}, {"name": "Void Vinnie", "bio": "Produces nothing."}]',
 '["A blank toxicology report."]',
 300);
